### PR TITLE
Fix: data.js error in YFLUSDYFLPool

### PR DESCRIPTION
**Pull request by tec05**
Working on verifying contracts now.

### CODE REVIEW

**Comment by tec05** [comment]
I have update all contracts. Sorry again for the missed steps.

**Comment by vfat-tools** [comment]
You're supposed to test the code by running it locally first. This still did not work.

**Comment by vfat-tools** [comment]
I have made some fixes and added it to vfat.tools/yflusd

**Comment by tec05** [comment]
Sorry about that, again.

Do you still accept tips here: 0x4BC821fef2ff947B57585a5FDBC73690Db288A49 or https://gitcoin.co/grants/1005/yieldfarminginfo?

**Comment by vfat-tools** [comment]
No worries, I certainly appreciate you taking the time to submit the PR. My site is a fork of yieldfarming.info so the original work was done by them, I have just taken over the baton. Feel free to donate to either, my Gitcoin link is on the footer at vfat.tools.
________________________________

**Comment by tec05** [comment]
Thanks so much!

https://gitcoin.co/townsquare?tab=activity:558746

**Pull request merged**
