### PR TITLE
Adding rainfinance

### PR DESCRIPTION
**Pull request by snappycreeper**
rainfinance - harmony

### CODE REVIEW

**Comment by Dimosgr** [comment]
Could you please verify the contract 0x250d3098c31dc0fe2ebe71eeecae806f434d9999 in order to add it?
Because this does not work. you have wrong function calls.

image

**Comment by snappycreeper** [comment]
https://github.com/snappycreeper/rain-contracts/blob/main/contracts/MasterChef.sol

This is the contract I used, its from goosedefi

**Comment by Dimosgr** [comment]
Ok i found the error from the link that you sent me thanks. It eggPerBlock not mochiPerBlock. Now it works :)
Please wait for the next update in order to see it.

**Comment by snappycreeper** [comment]
Thanks!

**Pull request merged**
