### PR TITLE
Add Bancor

### PR DESCRIPTION
**Pull request by ashachaf**
adding Bancor to the list.
changed 2 files:
src/static/js/all.js
pages/bancor/index.ejs

### CODE REVIEW

**Comment by Dimosgr** [comment]
Hi there. You are missing the script file which is interacting with the functions of the smart contract and shows the data.

**Comment by ashachaf** [comment]
@Dimosgr 
can you point the resource to follow for this data?
what information should i expose from the contact?
if we have an API with this data, can we pull this in?

**Comment by Dimosgr** [comment]
Basically you need the farming contract. Is it a masterchef for example? The information who you need is the staking tokens, the rewards destribution and functions for the user information (how much he has staked, earnings etc...)

**Comment by Dimosgr** [comment]
Added V3

**Pull request closed without merging**
