### PR TITLE
merged master and updated index.

### PR DESCRIPTION
**Pull request by neilfinleyas**
Renamed venom to venomswap

### CODE REVIEW

**Comment by vfat0** [comment]
sorry I don't quite understand, is this single file all you want to change? all changes need to be in a single pull request

**Comment by neilfinleyas** [comment]
I want to change the name from venom to venomswap in the index.js. And also renamed it from VENOM to venomswap in bsc.js

And they are new project so it should be lower on the list. Thanks.

**Comment by vfat0** [comment]
please see above, this pull request has only 1 File Changed, so it is not complete. I suggest starting from scratch to create a complete pull request

**Comment by neilfinleyas** [comment]
Sure okay thanks will do

**Pull request closed without merging**
