### PR TITLE
It Ain't Much But it's Honest Work

### PR DESCRIPTION
**Pull request by HonestWorkFarm**
The first experimental fixed supply deflationary yield farm on polygon.

### CODE REVIEW

**Comment by HonestWorkFarm** [comment]
Thank You!!! If i need to update anything can i just merge again?

**Comment by vfat0** [comment]
You need to do a new pull request for any changes, thanks for the PR!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by HonestWorkFarm** [comment]
Yes i might have to do it!! Have a wonderfull Solstice!!!

**Comment by vfat0** [comment]
your PR broke the site, please test it locally before submitting...

**Pull request merged**
