### PR TITLE
Add PolyMaple project

### PR DESCRIPTION
**Pull request by PolyMaple**
Add PolyMaple project

### CODE REVIEW

**Comment by vfat0** [comment]
please test this locally using the instructions on the readme, this is currently loading the wrong js file
image

**Comment by PolyMaple** [comment]
I am trying to set it locally in Windows OS, but I get "Cannot GET /"

**Comment by vfat0** [comment]
To test in windows the easiest way is to use WSL. Cannot get / seems to imply that the server is not running (`npm run dev` should run and say listening on localhost:3000)

**Comment by PolyMaple** [comment]
Tested locally:
image

**Pull request merged**
