### PR TITLE
Adding Matrix Finance

### PR DESCRIPTION
**Pull request by STZ5**

### CODE REVIEW

**Review by STZ5 — COMMENTED** [review]
Added Matrix in homepage

**Comment by Dimosgr** [comment]
Hi, you are using a contract address from another project to your logic file (https://cronos.crypto.org/explorer/address/0xD720528902c832e466bFEddfa60eCeb3A175ca1C/read-contract).
In this address 0xD720528902c832e466bFEddfa60eCeb3A175ca1C are the functions from genesis project. Please update it with the address of your project.

**Comment by STZ5** [comment]
> Hi, you are using a contract address from another project to your logic file (https://cronos.crypto.org/explorer/address/0xD720528902c832e466bFEddfa60eCeb3A175ca1C/read-contract). In this address 0xD720528902c832e466bFEddfa60eCeb3A175ca1C are the functions from genesis project. Please update it with the address of your project.

Hey Dimosgr, thanks for catching. I duplicated one of the cronos project and I didn't change the most important thing eheheh

Now we should be good

**Comment by Dimosgr** [comment]
ok yes now its perfect :)

**Pull request merged**
