### PR TITLE
Holdbox

### PR DESCRIPTION
**Pull request by HoldBox**

### CODE REVIEW

**Comment by Dimosgr** [comment]
Hi there, you are missing the logic file with the code which interacts with the staking contract. Please let me know if I can help.

**Comment by HoldBox** [comment]
> Hi there, you are missing the logic file with the code which interacts with the staking contract. Please let me know if I can help.

Hi.
Surely you can help me, I'm new to all this. lol

I want to list my project in Yield Farming Info, which file do you mean? 
I attached the index.ejs file. this is not a file right?

TY

**Comment by Dimosgr** [comment]
No because we are showing statistics of the farms. Thus, index.ejs will just show the name of the project and not the details of the farming.

The logic file is the file which interacts with the smart contract. I can add it but you need to send me the address of the staking contract in order to see the code. Do you have it?

**Comment by HoldBox** [comment]
I don't have this logic file, but if you give me an example I can do it.
Here is the bscscan address of my token:
https://bscscan.com/token/0xDB2eD1B8Af1B3d094b956ED383d3EBCeA1ed2277

**Comment by Dimosgr** [comment]
an example of a completed project is this.
https://github.com/vfat-tools/vfat-tools/commit/26100f676b09317a9eeea8f93585527f203fb720
there are three files. the index file calls the logic file and shows the results of the farming.

I need the address of the farming not from the token.

**Comment by HoldBox** [comment]
Thanks
my boss asked me to do this but I'm not getting it, I'm not familiar with codes. I'm having trouble with line 6 (bsc_name.js)
src/static/js/bsc.js
src/static/js/bsc_cerberus.js
src/views/pages/bsc/cerberus/index.ejs

How many do you want to help me with this? Help me promote the token on vfat.tools

thanks

**Comment by Dimosgr** [comment]
Hi again. Im not getting paid this is for free. the problem is that we are not promote tokens to vfat. We are just showing farming infos. The problem is that your site does not have farming, just your tokens details.

**Comment by Dimosgr** [comment]
closed because of inactivation.

**Pull request closed without merging**
