### PR TITLE
mistswap: add xMIST staking to calculator

### PR DESCRIPTION
**Pull request by mainnet-pat**
Also fix link to analytics pair stats
Add links to all smartbch dexes

### CODE REVIEW

**Comment by mainnet-pat** [comment]
image
image

**Comment by mainnet-pat** [comment]
Can you please deploy this code?

**Comment by Dimosgr** [comment]
Hi there. the project has been listed. Do you need something more?

**Comment by vfat0** [comment]
it wasn't deployed yet, all done now

**Pull request merged**
