### PR TITLE
Bdollar: Update APY, add button Approve, Stake, Unstake, Revoke

### PR DESCRIPTION
**Pull request by thanhnguyennguyen**
Changes in this PR:
- Update APY of staking pools
- Add `estimate Earning`
- Add button Approve, Stake, Unstake, Revoke
- Add link to the front page

### CODE REVIEW

**Comment by vfat-tools** [comment]
Hey just a quick note, I am not adding projects to the home page currently unless they are well established (like 8-9 figure TVL), but I am considering a revamp

**Comment by thanhnguyennguyen** [comment]
@vfat-tools Got it. Thank you

**Comment by vfat-tools** [comment]
these changes are good, can you try to add Stake and Unstake buttons as well?

**Comment by thanhnguyennguyen** [comment]
Yes, will do it

**Comment by thanhnguyennguyen** [comment]
Hi @vfat-tools 
I already updated following your suggestion.
Please help to review
Thank you so much

Let's farm sBDO with us 🚀

**Pull request merged**
