### PR TITLE
Fixed issue with wrong variable reward token Gator

### PR DESCRIPTION
**Pull request by terencelimzhengwei**

### CODE REVIEW

**Comment by vfat-tools** [comment]
this is still wrong unfortunately, the APRs are not calculated correctly 
image

**Comment by vfat-tools** [comment]
sorry maybe that is right it just hasn't started, my bad

**Comment by terencelimzhengwei** [comment]
No worries. Thanks!

Anyway wanted to check why I'm facing an issue when I'm testing on local.

I have an issue of me being on eth network instead of smart chain

**Comment by vfat-tools** [comment]
Haven't heard something like that before, can you find me on telegram @vfat0 to send me more info please

**Pull request merged**
