### PR TITLE
Added GYSR POOL

### PR DESCRIPTION
**Pull request by LeifuChen**
Xdollar launched a new liquidity pool on GYSR with IRON LP xUSD-IS3USD.

### CODE REVIEW

**Comment by Dimosgr** [comment]
This does not work and the contract of the pool that you added is not verified in order to fix it.

**Comment by LeifuChen** [comment]
@Dimosgr Sorry that I haven't got your idea. What do you mean "this does not work"?  Could you please speicify more about your suggestion? Thanks.
The main idea of this pull request is showing estimated APR of this new pool, which is missing from both GYSR, IRON SWAP and xDollar website. I redirected all the contract interaction to GYSR page so the user can operate on GYSR website.

**Comment by Dimosgr** [comment]
Yes there is a problem in print function of the pool because the info object is undefined. Did you run it locally and it worked for you?

**Comment by LeifuChen** [comment]
Yes. I have tested locally and it's running quite well with the wallet with GYSR pool staking. Do you mean it's not working with the wallet without GYSR pool staking? Let me try a new wallet to verify it. Thanks.

**Comment by LeifuChen** [comment]
@Dimosgr The bug has been fixed. Please verify it once more. Thanks.

**Comment by Dimosgr** [comment]
Yes it works perfect thanks

**Pull request merged**
