### PR TITLE
Add money maker

### PR DESCRIPTION
**Pull request by theanon1anon2anon3anon4anon5**

### CODE REVIEW

**Comment by MaticStake** [comment]
Do not accept this PR. It links to bnb_stake which is not his contract

**Comment by theanon1anon2anon3anon4anon5** [comment]
Apologies. Must have committed the wrong code last time. This time bnb_money_maker is all that is contributed, no editing existing files.

**Comment by MaticStake** [comment]
No, you changed the contract address of my bnb_stake PR 

This is your scammer PR
https://github.com/vfat-tools/vfat-tools/pull/1480

And this is my fix

https://github.com/vfat-tools/vfat-tools/pull/1499/commits/d5a310563daaa08c67c237ab321fa137fe9e8cf5


it’s easy to check this is the same person — the contract is the same and so is his wallet

**Comment by mathandley** [comment]
Also his his ftm_stake page falsely claims his is affiliated with matic stake which is untrue.

He's just a bottom feeder

**Pull request closed without merging**
